---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "remove dependencies that are no longer required"
    become: yes
    apt:
      autoremove: yes

  - name: "install nodejs and npm"
    become: yes
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: "install n"
    become: yes
    npm:
      name: n
      global: yes
      production: yes

  - name: "install nodejs 13.8.0"
    become: yes
    shell: n 13.8.0

  - name: "export .env"
    become: yes
    shell: |
      export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}"
      export TYPEORM_ENTITIES="{{ lookup('env', 'TYPEORM_ENTITIES') }}"
      export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME') }}"
      export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE') }}"

  - name: "install pm2"
    become: yes
    npm:
      name: pm2
      global: yes
      production: yes
      state: present
